window.recipeImages = {
"Banitsa": "https://source.unsplash.com/640x420/?banitsa,pastry,cheese",
"Shopska Salad": "https://source.unsplash.com/640x420/?salad,tomato,feta",
"Carbonara": "https://source.unsplash.com/640x420/?carbonara,pasta,bacon",
"Margherita Pizza": "https://source.unsplash.com/640x420/?pizza,mozzarella,basil",
"Ramen": "https://source.unsplash.com/640x420/?ramen,noodles,soup",
"Sushi Rice": "https://source.unsplash.com/640x420/?sushi,rice,japanese",
"Ratatouille": "https://source.unsplash.com/640x420/?ratatouille,vegetables,french",
"Crepes": "https://source.unsplash.com/640x420/?crepes,pancakes,french",
"Tacos": "https://source.unsplash.com/640x420/?tacos,mexican,tortillas",
"Guacamole": "https://source.unsplash.com/640x420/?guacamole,avocado,dip",
"Butter Chicken": "https://source.unsplash.com/640x420/?butterchicken,curry,indian",
"Palak Paneer": "https://source.unsplash.com/640x420/?palakpaneer,spinach,indian",
"Biryani": "https://source.unsplash.com/640x420/?biryani,rice,indian",
"Greek Salad": "https://source.unsplash.com/640x420/?greeksalad,feta,olives",
"Moussaka": "https://source.unsplash.com/640x420/?moussaka,eggplant,greek",
"Souvlaki": "https://source.unsplash.com/640x420/?souvlaki,grilled,meat",
"Baklava": "https://source.unsplash.com/640x420/?baklava,pastry,mediterranean",
"Kebab": "https://source.unsplash.com/640x420/?kebab,grilled,turkish",
"Lahmacun": "https://source.unsplash.com/640x420/?lahmacun,turkish,flatbread",
"Pide": "https://source.unsplash.com/640x420/?pide,turkish,pizza",
"Dim Sum": "https://source.unsplash.com/640x420/?dimsum,chinese,dumplings",
"Peking Duck": "https://source.unsplash.com/640x420/?pekingduck,chinese,roast",
"Kung Pao Chicken": "https://source.unsplash.com/640x420/?kungpao,chicken,spicy",
"Sweet and Sour Pork": "https://source.unsplash.com/640x420/?sweetandsour,pork,chinese",
"Fried Rice": "https://source.unsplash.com/640x420/?friedrice,chinese,rice",
"Spring Rolls": "https://source.unsplash.com/640x420/?springrolls,chinese,appetizer",
"Paella": "https://source.unsplash.com/640x420/?paella,spanish,seafood",
"Gazpacho": "https://source.unsplash.com/640x420/?gazpacho,soup,spanish",
"Tortilla Española": "https://source.unsplash.com/640x420/?tortilla,potatoes,spanish",
"Churros con Chocolate": "https://source.unsplash.com/640x420/?churros,chocolate,dessert",
"Dal": "https://source.unsplash.com/640x420/?dal,lentils,indian",
"Tzatziki": "https://source.unsplash.com/640x420/?tzatziki,yogurt,greek",
"Kebap": "https://source.unsplash.com/640x420/?kebap,grilled,turkish",
"Lasagna": "https://source.unsplash.com/640x420/?lasagna,pasta,italian",
"Gnocchi": "https://source.unsplash.com/640x420/?gnocchi,pasta,potato",
"Risotto": "https://source.unsplash.com/640x420/?risotto,rice,italian",
"Tiramisu": "https://source.unsplash.com/640x420/?tiramisu,coffee,italian",
"Bruschetta": "https://source.unsplash.com/640x420/?bruschetta,tomatoes,italian",
"Osso Buco": "https://source.unsplash.com/640x420/?ossobuco,veal,italian",
"Sashimi": "https://source.unsplash.com/640x420/?sashimi,fish,japanese",
"Tempura": "https://source.unsplash.com/640x420/?tempura,shrimp,japanese",
"Yakitori": "https://source.unsplash.com/640x420/?yakitori,chicken,japanese",
"Miso Soup": "https://source.unsplash.com/640x420/?misosoup,tofu,japanese",
"Udon": "https://source.unsplash.com/640x420/?udon,noodles,japanese",
"Coq au Vin": "https://source.unsplash.com/640x420/?coqauvin,chicken,french",
"Bouillabaisse": "https://source.unsplash.com/640x420/?bouillabaisse,fish,french",
"Quiche Lorraine": "https://source.unsplash.com/640x420/?quiche,bacon,french",
"French Onion Soup": "https://source.unsplash.com/640x420/?onionsoup,french,soup",
"Croissants": "https://source.unsplash.com/640x420/?croissants,pastry,french",
"Enchiladas": "https://source.unsplash.com/640x420/?enchiladas,mexican,cheese",
"Quesadillas": "https://source.unsplash.com/640x420/?quesadillas,mexican,tortillas",
"Nachos": "https://source.unsplash.com/640x420/?nachos,mexican,cheese",
"Pozole": "https://source.unsplash.com/640x420/?pozole,mexican,soup",
"Chiles Rellenos": "https://source.unsplash.com/640x420/?chilesrelenos,mexican,peppers",
"Sopa de Lima": "https://source.unsplash.com/640x420/?sopadelima,mexican,soup",
"Cochinita Pibil": "https://source.unsplash.com/640x420/?cochinita,mexican,pork",
"Huevos Rancheros": "https://source.unsplash.com/640x420/?huevosrancheros,mexican,eggs",
"Mole Poblano": "https://source.unsplash.com/640x420/?mole,mexican,chicken",
"Dumplings": "https://source.unsplash.com/640x420/?dumplings,chinese,steamed",
"Tarator": "https://source.unsplash.com/640x420/?tarator,soup,bulgarian",
"Minestrone": "https://source.unsplash.com/640x420/?minestrone,soup,italian",
"Caprese Salad": "https://source.unsplash.com/640x420/?caprese,tomatoes,italian",
"Panna Cotta": "https://source.unsplash.com/640x420/?pannacotta,cream,italian",
"Arancini": "https://source.unsplash.com/640x420/?arancini,rice,italian",
"Focaccia": "https://source.unsplash.com/640x420/?focaccia,bread,italian",
"Gnocchi di Patate": "https://source.unsplash.com/640x420/?gnocchi,potatoes,italian",
"Polenta": "https://source.unsplash.com/640x420/?polenta,corn,italian",
"Cannoli": "https://source.unsplash.com/640x420/?cannoli,ricotta,italian",
"Bottarga": "https://source.unsplash.com/640x420/?bottarga,fish,italian",
"Fritto Misto": "https://source.unsplash.com/640x420/?fritto,seafood,italian",
"Cacciucco": "https://source.unsplash.com/640x420/?cacciucco,soup,italian",
"Tonno al Forno": "https://source.unsplash.com/640x420/?tonno,tuna,italian",
"Branzino": "https://source.unsplash.com/640x420/?branzino,fish,italian",
"Saltimbocca": "https://source.unsplash.com/640x420/?saltimbocca,veal,italian",
"Cotoletta": "https://source.unsplash.com/640x420/?cotoletta,pork,italian",
"Ribollita": "https://source.unsplash.com/640x420/?ribollita,soup,italian",
"Pici": "https://source.unsplash.com/640x420/?pici,pasta,italian",
"Lardo di Colonnata": "https://source.unsplash.com/640x420/?lardo,pork,italian",
"Burrata": "https://source.unsplash.com/640x420/?burrata,cheese,italian",
"Pasta e Fagioli": "https://source.unsplash.com/640x420/?pastafagioli,soup,italian",
"Fagioli all'Uccelletto": "https://source.unsplash.com/640x420/?fagioli,beans,italian",
"Schiacciata": "https://source.unsplash.com/640x420/?schiacciata,bread,italian",
"Crespelle": "https://source.unsplash.com/640x420/?crespelle,pancakes,italian",
"Croquette di Patate": "https://source.unsplash.com/640x420/?croquette,potatoes,italian",
"Gelato": "https://source.unsplash.com/640x420/?gelato,icecream,italian",
"Sorbetto": "https://source.unsplash.com/640x420/?sorbetto,ice,italian",
"Chicken Teriyaki": "https://source.unsplash.com/640x420/?teriyaki,chicken,japanese",
"Nicoise Salad": "https://source.unsplash.com/640x420/?nicoise,tuna,french",
"Quesadilla": "https://source.unsplash.com/640x420/?quesadilla,cheese,mexican",
"Souvlaki": "https://source.unsplash.com/640x420/?souvlaki,pork,greek",
"Kebab": "https://source.unsplash.com/640x420/?kebab,meat,grilled",
"Spanakopita": "https://source.unsplash.com/640x420/?spanakopita,spinach,greek",
"Dolmades": "https://source.unsplash.com/640x420/?dolmades,grapeleaves,greek",
"Pastitsio": "https://source.unsplash.com/640x420/?pastitsio,pasta,greek",
"Saganaki": "https://source.unsplash.com/640x420/?saganaki,cheese,greek",
"Horiatiki": "https://source.unsplash.com/640x420/?horiatiki,salad,greek",
"Kleftiko": "https://source.unsplash.com/640x420/?kleftiko,lamb,greek",
"Baklava": "https://source.unsplash.com/640x420/?baklava,pastry,greek",
"Loukoumades": "https://source.unsplash.com/640x420/?loukoumades,doughnuts,greek",
"Galaktoboureko": "https://source.unsplash.com/640x420/?galaktoboureko,cream,greek",
"Melomakarona": "https://source.unsplash.com/640x420/?melomakarona,honey,greek",
"Kourabiedes": "https://source.unsplash.com/640x420/?kourabiedes,cookies,greek",
"Revani": "https://source.unsplash.com/640x420/?revani,cake,greek",
"Mosaiko": "https://source.unsplash.com/640x420/?mosaiko,chocolate,greek",
"Portokalopita": "https://source.unsplash.com/640x420/?portokalopita,orange,greek",
"Amygdalota": "https://source.unsplash.com/640x420/?amygdalota,almonds,greek",
"Rizogalo": "https://source.unsplash.com/640x420/?rizogalo,rice,greek",
"Fakes": "https://source.unsplash.com/640x420/?fakes,lentils,greek",
"Fasolada": "https://source.unsplash.com/640x420/?fasolada,beans,greek",
"Kolokithakia": "https://source.unsplash.com/640x420/?kolokithakia,zucchini,greek",
"Bamies": "https://source.unsplash.com/640x420/?bamies,okra,greek",
"Spanakorizo": "https://source.unsplash.com/640x420/?spanakorizo,spinach,greek",
"Yemista": "https://source.unsplash.com/640x420/?yemista,vegetables,greek",
"Menemen": "https://source.unsplash.com/640x420/?menemen,eggs,turkish",
"Mapo Tofu": "https://source.unsplash.com/640x420/?mapotofu,tofu,chinese",
"Kavarma": "https://source.unsplash.com/640x420/?kavarma,meat,bulgarian",
"Sarmi": "https://source.unsplash.com/640x420/?sarmi,cabbage,bulgarian",
"Kyopolou": "https://source.unsplash.com/640x420/?kyopolou,eggplant,bulgarian",
"Lukanka": "https://source.unsplash.com/640x420/?lukanka,sausage,bulgarian",
"Sudzhuk": "https://source.unsplash.com/640x420/?sudzhuk,sausage,bulgarian",
"Kiselo Mlyako": "https://source.unsplash.com/640x420/?kiselo,yogurt,bulgarian",
"Shkembe Chorba": "https://source.unsplash.com/640x420/?shkembe,soup,bulgarian",
"Bob Chorba": "https://source.unsplash.com/640x420/?bob,soup,bulgarian",
"Meshana Skara": "https://source.unsplash.com/640x420/?meshana,grilled,bulgarian",
"Karnache": "https://source.unsplash.com/640x420/?karnache,sausage,bulgarian",
"Kebapcheta": "https://source.unsplash.com/640x420/?kebapcheta,grilled,bulgarian",
"Purjeni Chushki": "https://source.unsplash.com/640x420/?purjeni,peppers,bulgarian",
"Patatnik": "https://source.unsplash.com/640x420/?patatnik,potatoes,bulgarian",
"Chushki Vrushki": "https://source.unsplash.com/640x420/?chushki,peppers,bulgarian",
"Parleni Chushki": "https://source.unsplash.com/640x420/?parleni,peppers,bulgarian",
"Zelnik": "https://source.unsplash.com/640x420/?zelnik,pastry,bulgarian",
"Mekitsa": "https://source.unsplash.com/640x420/?mekitsa,doughnuts,bulgarian",
"Kozunak": "https://source.unsplash.com/640x420/?kozunak,bread,bulgarian",
"Tikvenik": "https://source.unsplash.com/640x420/?tikvenik,pumpkin,bulgarian",
"Rozhen": "https://source.unsplash.com/640x420/?rozhen,grilled,bulgarian",
"Kavarma na Sach": "https://source.unsplash.com/640x420/?kavarma,sach,bulgarian",
"Skarlatina": "https://source.unsplash.com/640x420/?skarlatina,soup,bulgarian",
"Vrushki": "https://source.unsplash.com/640x420/?vrushki,peppers,bulgarian",
"Pileshka Supa": "https://source.unsplash.com/640x420/?pileshka,soup,bulgarian",
"Topcheta": "https://source.unsplash.com/640x420/?topcheta,meatballs,bulgarian",
"Pacha": "https://source.unsplash.com/640x420/?pacha,soup,bulgarian",
"Kapama": "https://source.unsplash.com/640x420/?kapama,stew,bulgarian",
"Punjeni Papriki": "https://source.unsplash.com/640x420/?punjeni,peppers,bulgarian",
"Kiselo Zelk": "https://source.unsplash.com/640x420/?kiselo,sauerkraut,bulgarian",
"Oshav": "https://source.unsplash.com/640x420/?oshav,compote,bulgarian",
"Pachaver": "https://source.unsplash.com/640x420/?pachaver,pastry,bulgarian",
"Kifla": "https://source.unsplash.com/640x420/?kifla,bread,bulgarian",
"Pitka": "https://source.unsplash.com/640x420/?pitka,bread,bulgarian",
"Lutenitsa": "https://source.unsplash.com/640x420/?lutenitsa,spread,bulgarian",
"Snejanka": "https://source.unsplash.com/640x420/?snejanka,salad,bulgarian",
"Rozmarin": "https://source.unsplash.com/640x420/?rozmarin,chicken,bulgarian",
"Krem Karamel": "https://source.unsplash.com/640x420/?kremkaramel,cream,bulgarian",
"Garash": "https://source.unsplash.com/640x420/?garash,cake,bulgarian",
"Tulumbi": "https://source.unsplash.com/640x420/?tulumbi,dessert,bulgarian",
"Lokum": "https://source.unsplash.com/640x420/?lokum,delight,bulgarian",
"Sutliash": "https://source.unsplash.com/640x420/?sutliash,rice,bulgarian",
"Mlechna Shampola": "https://source.unsplash.com/640x420/?mlechna,cake,bulgarian",
"Kashkaval Pane": "https://source.unsplash.com/640x420/?kashkaval,cheese,bulgarian",
"Princess": "https://source.unsplash.com/640x420/?princess,cake,bulgarian",
"Ekler": "https://source.unsplash.com/640x420/?ekler,cream,bulgarian",
"Madzuni": "https://source.unsplash.com/640x420/?madzuni,soup,bulgarian",
"Ribena Chorba": "https://source.unsplash.com/640x420/?ribena,soup,bulgarian",
"Domashna Supa": "https://source.unsplash.com/640x420/?domashna,soup,bulgarian",
"Kartofi Kusha": "https://source.unsplash.com/640x420/?kartofi,potatoes,bulgarian",
"Zelen Chorba": "https://source.unsplash.com/640x420/?zelen,soup,bulgarian",
"Loboda": "https://source.unsplash.com/640x420/?loboda,soup,bulgarian",
"Kopriva": "https://source.unsplash.com/640x420/?kopriva,soup,bulgarian",
"Nettle": "https://source.unsplash.com/640x420/?nettle,soup,bulgarian",
"Parni": "https://source.unsplash.com/640x420/?parni,dumplings,bulgarian",
"Kashkavalki": "https://source.unsplash.com/640x420/?kashkavalki,cheese,bulgarian",
"Risotto Milanese": "https://source.unsplash.com/640x420/?risotto,saffron,italian",
"Gnocchi": "https://source.unsplash.com/640x420/?gnocchi,potato,italian",
"Affogato": "https://source.unsplash.com/640x420/?affogato,coffee,italian",
"Pizzelle": "https://source.unsplash.com/640x420/?pizzelle,waffles,italian",
"Zeppole": "https://source.unsplash.com/640x420/?zeppole,doughnuts,italian",
"Sfogliatelle": "https://source.unsplash.com/640x420/?sfogliatelle,pastry,italian",
"Cassata": "https://source.unsplash.com/640x420/?cassata,ricotta,italian",
"Granita": "https://source.unsplash.com/640x420/?granita,ice,italian",
"Semifreddo": "https://source.unsplash.com/640x420/?semifreddo,cream,italian",
"Zuccotto": "https://source.unsplash.com/640x420/?zuccotto,cake,italian",
"Torta della Nonna": "https://source.unsplash.com/640x420/?torta,cream,italian",
"Crostata": "https://source.unsplash.com/640x420/?crostata,pie,italian",
"Ciabatta": "https://source.unsplash.com/640x420/?ciabatta,bread,italian",
"Grissini": "https://source.unsplash.com/640x420/?grissini,breadsticks,italian",
"Taralli": "https://source.unsplash.com/640x420/?taralli,bread,italian",
"Friselle": "https://source.unsplash.com/640x420/?friselle,bread,italian",
"Pane di Altamura": "https://source.unsplash.com/640x420/?panedi,bread,italian",
"Pane Carasau": "https://source.unsplash.com/640x420/?panecarasau,bread,italian",
"Piadina": "https://source.unsplash.com/640x420/?piadina,flatbread,italian",
"Prosciutto di Parma": "https://source.unsplash.com/640x420/?prosciutto,ham,italian",
"Pancetta": "https://source.unsplash.com/640x420/?pancetta,bacon,italian",
"Guanciale": "https://source.unsplash.com/640x420/?guanciale,pork,italian",
"Coppa": "https://source.unsplash.com/640x420/?coppa,pork,italian",
"Bottarga": "https://source.unsplash.com/640x420/?bottarga,roe,italian",
"Caponata": "https://source.unsplash.com/640x420/?caponata,eggplant,italian",
"Bistecca alla Fiorentina": "https://source.unsplash.com/640x420/?bistecca,steak,italian",
"Sushi Platter": "https://source.unsplash.com/640x420/?sushi,platter,japanese",
"Ramen": "https://source.unsplash.com/640x420/?ramen,noodles,japanese",
"Dim Sum": "https://source.unsplash.com/640x420/?dimsum,dumplings,chinese",
"Peking Duck": "https://source.unsplash.com/640x420/?pekingduck,duck,chinese",
"Kung Pao Chicken": "https://source.unsplash.com/640x420/?kungpao,chicken,chinese",
"Fried Rice": "https://source.unsplash.com/640x420/?friedrice,rice,chinese",
"Spring Rolls": "https://source.unsplash.com/640x420/?springrolls,appetizer,chinese",
"Dumplings": "https://source.unsplash.com/640x420/?dumplings,steamed,chinese",
"Wonton Soup": "https://source.unsplash.com/640x420/?wontonsoup,dumplings,chinese",
"Hot and Sour Soup": "https://source.unsplash.com/640x420/?hotsour,soup,chinese",
"Egg Drop Soup": "https://source.unsplash.com/640x420/?eggdrop,soup,chinese",
"Wontons": "https://source.unsplash.com/640x420/?wontons,dumplings,chinese",
"Char Siu": "https://source.unsplash.com/640x420/?charsiu,pork,chinese",
"Pork Buns": "https://source.unsplash.com/640x420/?porkbuns,steamed,chinese",
"Beef and Broccoli": "https://source.unsplash.com/640x420/?beefbroccoli,stirfry,chinese",
"Kung Pao Tofu": "https://source.unsplash.com/640x420/?kungpao,tofu,chinese",
"Szechuan Chicken": "https://source.unsplash.com/640x420/?szechuan,chicken,chinese",
"Mongolian Beef": "https://source.unsplash.com/640x420/?mongolian,beef,chinese",
"General Tso's Chicken": "https://source.unsplash.com/640x420/?generaltsos,chicken,chinese",
"Lo Mein": "https://source.unsplash.com/640x420/?lomein,noodles,chinese",
"Chow Mein": "https://source.unsplash.com/640x420/?chowmein,noodles,chinese",
"Chow Fun": "https://source.unsplash.com/640x420/?chowfun,noodles,chinese",
"Egg Foo Young": "https://source.unsplash.com/640x420/?eggfoo,omelet,chinese",
"Fortune Cookies": "https://source.unsplash.com/640x420/?fortune,cookies,chinese",
"Katsudon": "https://source.unsplash.com/640x420/?katsudon,pork,japanese",
"Gyoza": "https://source.unsplash.com/640x420/?gyoza,dumplings,japanese",
"Tonkatsu": "https://source.unsplash.com/640x420/?tonkatsu,pork,japanese",
"Chawanmushi": "https://source.unsplash.com/640x420/?chawanmushi,egg,japanese",
"Okonomiyaki": "https://source.unsplash.com/640x420/?okonomiyaki,pancake,japanese",
"Takoyaki": "https://source.unsplash.com/640x420/?takoyaki,octopus,japanese",
"Yakizakana": "https://source.unsplash.com/640x420/?yakizakana,grilled,japanese",
"Sukiyaki": "https://source.unsplash.com/640x420/?sukiyaki,beef,japanese",
"Shabu Shabu": "https://source.unsplash.com/640x420/?shabushabu,hotpot,japanese",
"Oden": "https://source.unsplash.com/640x420/?oden,hotpot,japanese",
"Karaage": "https://source.unsplash.com/640x420/?karaage,chicken,japanese",
"Tamagoyaki": "https://source.unsplash.com/640x420/?tamagoyaki,omelet,japanese",
"Onigiri": "https://source.unsplash.com/640x420/?onigiri,rice,japanese",
"Soba": "https://source.unsplash.com/640x420/?soba,noodles,japanese",
"Tsukemen": "https://source.unsplash.com/640x420/?tsukemen,noodles,japanese",
"Yakisoba": "https://source.unsplash.com/640x420/?yakisoba,noodles,japanese",
"Maki Rolls": "https://source.unsplash.com/640x420/?maki,rolls,japanese",
"Nigiri": "https://source.unsplash.com/640x420/?nigiri,sushi,japanese",
"Chirashi": "https://source.unsplash.com/640x420/?chirashi,sushi,japanese",
"Inari": "https://source.unsplash.com/640x420/?inari,tofu,japanese",
"Edamame": "https://source.unsplash.com/640x420/?edamame,soybeans,japanese",
"Wakame Salad": "https://source.unsplash.com/640x420/?wakame,salad,japanese",
"Hiyayakko": "https://source.unsplash.com/640x420/?hiyayakko,tofu,japanese",
"Agedashi Tofu": "https://source.unsplash.com/640x420/?agedashi,tofu,japanese",
"Ebi Tempura": "https://source.unsplash.com/640x420/?ebitempura,shrimp,japanese",
"Kaki Fry": "https://source.unsplash.com/640x420/?kakifry,oysters,japanese",
"Matcha Ice Cream": "https://source.unsplash.com/640x420/?matcha,icecream,japanese",
"Boeuf Bourguignon": "https://source.unsplash.com/640x420/?boeuf,beef,french",
"Soufflé au Fromage": "https://source.unsplash.com/640x420/?souffle,cheese,french",
"Cassoulet": "https://source.unsplash.com/640x420/?cassoulet,beans,french",
"Confit de Canard": "https://source.unsplash.com/640x420/?confit,duck,french",
"Pain au Chocolat": "https://source.unsplash.com/640x420/?painau,chocolate,french",
"Éclair": "https://source.unsplash.com/640x420/?eclair,cream,french",
"Macarons": "https://source.unsplash.com/640x420/?macarons,cookies,french",
"Crème Brûlée": "https://source.unsplash.com/640x420/?cremebrulee,cream,french",
"Tarte Tatin": "https://source.unsplash.com/640x420/?tartetatin,apple,french",
"Madeleines": "https://source.unsplash.com/640x420/?madeleines,cakes,french",
"Profiteroles": "https://source.unsplash.com/640x420/?profiteroles,cream,french",
"Mille-Feuille": "https://source.unsplash.com/640x420/?millefeuille,pastry,french",
"Opera Cake": "https://source.unsplash.com/640x420/?opera,cake,french",
"Paris-Brest": "https://source.unsplash.com/640x420/?parisbrest,cream,french",
"Saint-Honoré": "https://source.unsplash.com/640x420/?sainthonore,cream,french",
"Fondant au Chocolat": "https://source.unsplash.com/640x420/?fondant,chocolate,french",
"Clafoutis": "https://source.unsplash.com/640x420/?clafoutis,cherry,french",
"Far Breton": "https://source.unsplash.com/640x420/?farbreton,prunes,french",
"Kouglof": "https://source.unsplash.com/640x420/?kouglof,cake,french",
"Pain de Campagne": "https://source.unsplash.com/640x420/?paindecampagne,bread,french",
"Baguette": "https://source.unsplash.com/640x420/?baguette,bread,french",
"Fougasse": "https://source.unsplash.com/640x420/?fougasse,bread,french",
"Pain aux Noix": "https://source.unsplash.com/640x420/?painnoix,nuts,french",
"Pain aux Raisins": "https://source.unsplash.com/640x420/?painraisins,raisins,french",
"Brioche": "https://source.unsplash.com/640x420/?brioche,bread,french",
"Pain au Levain": "https://source.unsplash.com/640x420/?painlevain,sourdough,french",
"Pot-au-Feu": "https://source.unsplash.com/640x420/?potaufeu,beef,french",
"Blanquette de Veau": "https://source.unsplash.com/640x420/?blanquette,veal,french",
"Navarin d'Agneau": "https://source.unsplash.com/640x420/?navarin,lamb,french",
"Choucroute Garnie": "https://source.unsplash.com/640x420/?choucroute,sauerkraut,french",
"Andouillette": "https://source.unsplash.com/640x420/?andouillette,sausage,french",
"Boudin Noir": "https://source.unsplash.com/640x420/?boudinnoir,bloodpudding,french",
"Rillettes": "https://source.unsplash.com/640x420/?rillettes,pork,french",
"Pâté de Campagne": "https://source.unsplash.com/640x420/?pate,pate,french",
"Terrine de Campagne": "https://source.unsplash.com/640x420/?terrine,pate,french",
"Quenelles": "https://source.unsplash.com/640x420/?quenelles,dumplings,french",
"Socca": "https://source.unsplash.com/640x420/?socca,chickpea,french",
"Pissaladière": "https://source.unsplash.com/640x420/?pissaladiere,onion,french",
"Calissons": "https://source.unsplash.com/640x420/?calissons,candy,french",
"Nougat": "https://source.unsplash.com/640x420/?nougat,nuts,french",
"Berlingots": "https://source.unsplash.com/640x420/?berlingots,candy,french",
"Canelés": "https://source.unsplash.com/640x420/?caneles,cake,french",
"Kouign-Amann": "https://source.unsplash.com/640x420/?kouign,butter,french",
"Galettes": "https://source.unsplash.com/640x420/?galettes,pancakes,french",
"Galette des Rois": "https://source.unsplash.com/640x420/?galettedesrois,cake,french",
"Pain Perdu": "https://source.unsplash.com/640x420/?painperdu,french,french",
"Œufs à la Coque": "https://source.unsplash.com/640x420/?oeufscoque,eggs,french",
"Croque-Monsieur": "https://source.unsplash.com/640x420/?croquemonsieur,ham,french",
"Croque-Madame": "https://source.unsplash.com/640x420/?croquemadame,ham,french",
"Jambon-Beurre": "https://source.unsplash.com/640x420/?jambonbeurre,ham,french",
"Salade Niçoise": "https://source.unsplash.com/640x420/?saladenicoise,tuna,french",
"Salade Lyonnaise": "https://source.unsplash.com/640x420/?saladelyonnaise,lardons,french",
"Salade au Chèvre Chaud": "https://source.unsplash.com/640x420/?saladechevre,goat,french",
"Soupe à l'Oignon": "https://source.unsplash.com/640x420/?soupeonion,onion,french",
"Soupe au Pistou": "https://source.unsplash.com/640x420/?soupepistou,basil,french",
"Soupe de Poisson": "https://source.unsplash.com/640x420/?soupepoisson,fish,french",
"Velouté": "https://source.unsplash.com/640x420/?veloute,soup,french",
"Consommé": "https://source.unsplash.com/640x420/?consomme,broth,french",
"Chiles Rellenos": "https://source.unsplash.com/640x420/?chilesrelenos,peppers,mexican",
"Mole Poblano": "https://source.unsplash.com/640x420/?mole,chicken,mexican",
"Pozole": "https://source.unsplash.com/640x420/?pozole,hominy,mexican",
"Cochinita Pibil": "https://source.unsplash.com/640x420/?cochinita,pork,mexican",
"Huevos Rancheros": "https://source.unsplash.com/640x420/?huevos,eggs,mexican",
"Menudo": "https://source.unsplash.com/640x420/?menudo,tripe,mexican",
"Barbacoa": "https://source.unsplash.com/640x420/?barbacoa,lamb,mexican",
"Carnitas": "https://source.unsplash.com/640x420/?carnitas,pork,mexican",
"Al Pastor": "https://source.unsplash.com/640x420/?alpastor,pork,mexican",
"Birria": "https://source.unsplash.com/640x420/?birria,goat,mexican",
"Tamales": "https://source.unsplash.com/640x420/?tamales,corn,mexican",
"Sopa de Lima": "https://source.unsplash.com/640x420/?sopadelima,lime,mexican",
"Caldo de Res": "https://source.unsplash.com/640x420/?caldores,beef,mexican",
"Caldo de Pollo": "https://source.unsplash.com/640x420/?caldopollo,chicken,mexican",
"Pozole Verde": "https://source.unsplash.com/640x420/?pozoleverde,green,mexican",
"Pozole Rojo": "https://source.unsplash.com/640x420/?pozolerojo,red,mexican",
"Pozole Blanco": "https://source.unsplash.com/640x420/?pozoleblanco,white,mexican",
"Tortas Ahogadas": "https://source.unsplash.com/640x420/?tortas,sandwich,mexican",
"Chilaquiles": "https://source.unsplash.com/640x420/?chilaquiles,tortillas,mexican",
"Molletes": "https://source.unsplash.com/640x420/?molletes,beans,mexican",
"Cemita Poblana": "https://source.unsplash.com/640x420/?cemita,sandwich,mexican",
"Torta de Milanesa": "https://source.unsplash.com/640x420/?tortamilanesa,beef,mexican",
"Pambazo": "https://source.unsplash.com/640x420/?pambazo,sandwich,mexican",
"Gorditas": "https://source.unsplash.com/640x420/?gorditas,corn,mexican",
"Sopes": "https://source.unsplash.com/640x420/?sopes,corn,mexican",
"Huaraches": "https://source.unsplash.com/640x420/?huaraches,corn,mexican",
"Tlacoyos": "https://source.unsplash.com/640x420/?tlacoyos,corn,mexican",
"Memelas": "https://source.unsplash.com/640x420/?memelas,corn,mexican",
"Tlayudas": "https://source.unsplash.com/640x420/?tlayudas,corn,mexican",
"Quesadillas": "https://source.unsplash.com/640x420/?quesadillas,cheese,mexican",
"Enchiladas": "https://source.unsplash.com/640x420/?enchiladas,corn,mexican",
"Enchiladas Verdes": "https://source.unsplash.com/640x420/?enchiladasverdes,green,mexican",
"Enchiladas Rojas": "https://source.unsplash.com/640x420/?enchiladasrojas,red,mexican",
"Enmoladas": "https://source.unsplash.com/640x420/?enmoladas,mole,mexican",
"Ceviche de Camarón": "https://source.unsplash.com/640x420/?ceviche,shrimp,mexican",
"Tostadas": "https://source.unsplash.com/640x420/?tostadas,corn,mexican",
"Tostadas de Ceviche": "https://source.unsplash.com/640x420/?tostadasceviche,shrimp,mexican",
"Tostadas de Tinga": "https://source.unsplash.com/640x420/?tostadastinga,chicken,mexican",
"Tostadas de Pata": "https://source.unsplash.com/640x420/?tostadaspata,beef,mexican",
"Tostadas de Jaiba": "https://source.unsplash.com/640x420/?tostadasjaiba,crab,mexican",
"Tostadas de Pollo": "https://source.unsplash.com/640x420/?tostadaspollo,chicken,mexican",
"Tostadas de Carne": "https://source.unsplash.com/640x420/?tostadascarne,beef,mexican",
"Tostadas de Pescado": "https://source.unsplash.com/640x420/?tostadaspescado,fish,mexican",
"Tostadas de Camarón": "https://source.unsplash.com/640x420/?tostadascamaron,shrimp,mexican",
"Tostadas de Tinga de Pollo": "https://source.unsplash.com/640x420/?tostadastingapollo,chicken,mexican",
"Tostadas de Ahogadas": "https://source.unsplash.com/640x420/?tostadasahogadas,pork,mexican",
"Tostadas de Barbacoa": "https://source.unsplash.com/640x420/?tostadasbarbacoa,lamb,mexican",
"Tostadas de Carnitas": "https://source.unsplash.com/640x420/?tostadascarnitas,pork,mexican",
"Tostadas de Al Pastor": "https://source.unsplash.com/640x420/?tostadasalpastor,pork,mexican",
"Tostadas de Birria": "https://source.unsplash.com/640x420/?tostadasbirria,goat,mexican",
"Tostadas de Mole": "https://source.unsplash.com/640x420/?tostadasmole,chicken,mexican",
"Tostadas de Chicharrón": "https://source.unsplash.com/640x420/?tostadaschicharron,pork,mexican",
"Tostadas de Huevo": "https://source.unsplash.com/640x420/?tostadashuevo,eggs,mexican",
"Tostadas de Frijoles": "https://source.unsplash.com/640x420/?tostadasfrijoles,beans,mexican",
"Tostadas de Aguacate": "https://source.unsplash.com/640x420/?tostadasaguacate,avocado,mexican",
"Tostadas de Queso": "https://source.unsplash.com/640x420/?tostadasqueso,cheese,mexican",
"Tostadas de Nopales": "https://source.unsplash.com/640x420/?tostadasnopales,cactus,mexican",
"Tostadas de Chapulines": "https://source.unsplash.com/640x420/?tostadaschapulines,grasshoppers,mexican",
"Tostadas de Escamoles": "https://source.unsplash.com/640x420/?tostadasescamoles,ant,eggs,mexican",
"Tostadas de Huitlacoche": "https://source.unsplash.com/640x420/?tostadashuitlacoche,corn,mexican",
"Tostadas de Flor de Calabaza": "https://source.unsplash.com/640x420/?tostadasflor,squash,mexican",
"Tostadas de Nopal": "https://source.unsplash.com/640x420/?tostadasnopal,cactus,mexican",
"Tostadas de Jamaica": "https://source.unsplash.com/640x420/?tostadasjamaica,hibiscus,mexican",
"Tostadas de Tamarindo": "https://source.unsplash.com/640x420/?tostadastamarindo,tamarind,mexican",
"Tostadas de Mango": "https://source.unsplash.com/640x420/?tostadasmango,mango,mexican",
"Tostadas de Piña": "https://source.unsplash.com/640x420/?tostadaspiña,pineapple,mexican",
"Tostadas de Plátano": "https://source.unsplash.com/640x420/?tostadasplatano,plantain,mexican",
"Tostadas de Coco": "https://source.unsplash.com/640x420/?tostadascoco,coconut,mexican",
"Tostadas de Fresa": "https://source.unsplash.com/640x420/?tostadasfresa,strawberry,mexican",
"Tostadas de Mamey": "https://source.unsplash.com/640x420/?tostadasmamey,mamey,mexican",
"Tostadas de Guayaba": "https://source.unsplash.com/640x420/?tostadasguayaba,guava,mexican",
"Flan de Naranja": "https://source.unsplash.com/640x420/?flan,orange,mexican",
"Chicken Tikka Masala": "https://source.unsplash.com/640x420/?chickentikka,chicken,indian",
"Butter Chicken": "https://source.unsplash.com/640x420/?butterchicken,chicken,indian",
"Samosas": "https://source.unsplash.com/640x420/?samosas,pastry,indian",
"Pakoras": "https://source.unsplash.com/640x420/?pakoras,fritters,indian",
"Korma": "https://source.unsplash.com/640x420/?korma,curry,indian",
"Vindaloo": "https://source.unsplash.com/640x420/?vindaloo,spicy,indian",
"Madras": "https://source.unsplash.com/640x420/?madras,curry,indian",
"Tikka Masala": "https://source.unsplash.com/640x420/?tikkamasala,chicken,indian",
"Chicken Korma": "https://source.unsplash.com/640x420/?chickenkorma,chicken,indian",
"Lamb Korma": "https://source.unsplash.com/640x420/?lambkorma,lamb,indian",
"Beef Korma": "https://source.unsplash.com/640x420/?beefkorma,beef,indian",
"Vegetable Korma": "https://source.unsplash.com/640x420/?vegkorma,vegetables,indian",
"Chicken Vindaloo": "https://source.unsplash.com/640x420/?chickenvindaloo,chicken,indian",
"Pork Vindaloo": "https://source.unsplash.com/640x420/?porkvindaloo,pork,indian",
"Lamb Vindaloo": "https://source.unsplash.com/640x420/?lambvindaloo,lamb,indian",
"Beef Vindaloo": "https://source.unsplash.com/640x420/?beefvindaloo,beef,indian",
"Vegetable Vindaloo": "https://source.unsplash.com/640x420/?vegvindaloo,vegetables,indian",
"Chicken Madras": "https://source.unsplash.com/640x420/?chickenmadras,chicken,indian",
"Lamb Madras": "https://source.unsplash.com/640x420/?lambmadras,lamb,indian",
"Beef Madras": "https://source.unsplash.com/640x420/?beefmadras,beef,indian",
"Vegetable Madras": "https://source.unsplash.com/640x420/?vegmadras,vegetables,indian",
"Goan Fish Curry": "https://source.unsplash.com/640x420/?goanfish,fish,indian",
"Malabar Fish Curry": "https://source.unsplash.com/640x420/?malabarfish,fish,indian",
"Kerala Fish Curry": "https://source.unsplash.com/640x420/?keralafish,fish,indian",
"Bengali Fish Curry": "https://source.unsplash.com/640x420/?bengalifish,fish,indian",
"Tamil Fish Curry": "https://source.unsplash.com/640x420/?tamilfish,fish,indian",
"Andhra Fish Curry": "https://source.unsplash.com/640x420/?andhrafish,fish,indian",
"Maharashtrian Fish Curry": "https://source.unsplash.com/640x420/?maharashtrianfish,fish,indian",
"Gujarati Fish Curry": "https://source.unsplash.com/640x420/?gujaratifish,fish,indian",
"Rajasthani Fish Curry": "https://source.unsplash.com/640x420/?rajasthanifish,fish,indian",
"Punjabi Fish Curry": "https://source.unsplash.com/640x420/?punjabifish,fish,indian",
"Kashmiri Fish Curry": "https://source.unsplash.com/640x420/?kashmirifish,fish,indian",
"Himachali Fish Curry": "https://source.unsplash.com/640x420/?himachalifish,fish,indian",
"Uttaranchali Fish Curry": "https://source.unsplash.com/640x420/?uttaranchalifish,fish,indian",
"Bihari Fish Curry": "https://source.unsplash.com/640x420/?biharifish,fish,indian",
"Rogan Josh": "https://source.unsplash.com/640x420/?roganjosh,lamb,indian",
"Masala Dosa": "https://source.unsplash.com/640x420/?masaladosa,dosa,indian",
"Chole Bhature": "https://source.unsplash.com/640x420/?cholebhature,chickpeas,indian",
"Idli": "https://source.unsplash.com/640x420/?idli,rice,indian",
"Dosa": "https://source.unsplash.com/640x420/?dosa,rice,indian",
"Uttapam": "https://source.unsplash.com/640x420/?uttapam,pancake,indian",
"Vada": "https://source.unsplash.com/640x420/?vada,donut,indian",
"Medu Vada": "https://source.unsplash.com/640x420/?meduvada,donut,indian",
"Onion Vada": "https://source.unsplash.com/640x420/?onionvada,donut,indian",
"Rava Vada": "https://source.unsplash.com/640x420/?ravavada,donut,indian",
"Maddur Vada": "https://source.unsplash.com/640x420/?maddurvada,donut,indian",
"Masala Vada": "https://source.unsplash.com/640x420/?masalavada,donut,indian",
"Dal Vada": "https://source.unsplash.com/640x420/?dalvada,donut,indian",
"Chana Dal Vada": "https://source.unsplash.com/640x420/?chanadalvada,donut,indian",
"Mung Dal Vada": "https://source.unsplash.com/640x420/?mungdalvada,donut,indian",
"Urad Dal Vada": "https://source.unsplash.com/640x420/?uraddalvada,donut,indian",
"Toor Dal Vada": "https://source.unsplash.com/640x420/?toordalvada,donut,indian",
"Masoor Dal Vada": "https://source.unsplash.com/640x420/?masoordalvada,donut,indian",
"Rajma": "https://source.unsplash.com/640x420/?rajma,beans,indian",
"Chana Masala": "https://source.unsplash.com/640x420/?chanamasala,chickpeas,indian",
"Chole": "https://source.unsplash.com/640x420/?chole,chickpeas,indian",
"Rajma Chawal": "https://source.unsplash.com/640x420/?rajmachawal,beans,indian",
"Dal Makhani": "https://source.unsplash.com/640x420/?dalmakhani,lentils,indian",
"Dal Tadka": "https://source.unsplash.com/640x420/?daltadka,lentils,indian",
"Dal Fry": "https://source.unsplash.com/640x420/?dalfry,lentils,indian",
"Dal Palak": "https://source.unsplash.com/640x420/?dalpalak,lentils,indian",
"Dal Mooli": "https://source.unsplash.com/640x420/?dalmooli,lentils,indian",
"Dal Methi": "https://source.unsplash.com/640x420/?dalmethi,lentils,indian",
"Dal Lauki": "https://source.unsplash.com/640x420/?dallauki,lentils,indian",
"Dal Kachori": "https://source.unsplash.com/640x420/?dalkachori,lentils,indian",
"Dal Pakwan": "https://source.unsplash.com/640x420/?dalpakwan,lentils,indian",
"Dal Puri": "https://source.unsplash.com/640x420/?dalpuri,lentils,indian",
"Dal Baati": "https://source.unsplash.com/640x420/?dalbaati,lentils,indian",
"Dal Bati": "https://source.unsplash.com/640x420/?dalbati,lentils,indian",
"Dal Chawal": "https://source.unsplash.com/640x420/?dalchawal,lentils,indian",
"Dal Roti": "https://source.unsplash.com/640x420/?dalroti,lentils,indian",
"Dal Paratha": "https://source.unsplash.com/640x420/?dalparatha,lentils,indian",
"Dal Naan": "https://source.unsplash.com/640x420/?dalnaan,lentils,indian",
"Dal Kulcha": "https://source.unsplash.com/640x420/?dalkulcha,lentils,indian",
"Gulab Jamun": "https://source.unsplash.com/640x420/?gulabjamun,dessert,indian",
"Baklava": "https://source.unsplash.com/640x420/?baklava,pastry,turkish",
"Iskender": "https://source.unsplash.com/640x420/?iskender,kebab,turkish",
"Adana Kebab": "https://source.unsplash.com/640x420/?adanakebab,kebab,turkish",
"Urfa Kebab": "https://source.unsplash.com/640x420/?urfakebab,kebab,turkish",
"Shish Kebab": "https://source.unsplash.com/640x420/?shishkebab,kebab,turkish",
"Doner Kebab": "https://source.unsplash.com/640x420/?donerkebab,kebab,turkish",
"Chicken Doner": "https://source.unsplash.com/640x420/?chickendon,kebab,turkish",
"Lamb Doner": "https://source.unsplash.com/640x420/?lambdon,kebab,turkish",
"Beef Doner": "https://source.unsplash.com/640x420/?beefdon,kebab,turkish",
"Mixed Doner": "https://source.unsplash.com/640x420/?mixeddon,kebab,turkish",
"Gyro": "https://source.unsplash.com/640x420/?gyro,meat,greek",
"Meze Platter": "https://source.unsplash.com/640x420/?mezepattern,appetizers,turkish",
"Hummus": "https://source.unsplash.com/640x420/?hummus,chickpeas,mediterranean",
"Falafel": "https://source.unsplash.com/640x420/?falafel,chickpeas,mediterranean",
"Tabbouleh": "https://source.unsplash.com/640x420/?tabbouleh,parsley,mediterranean",
"Baba Ghanoush": "https://source.unsplash.com/640x420/?babaghanoush,eggplant,mediterranean",
"Muhammara": "https://source.unsplash.com/640x420/?muhammara,peppers,mediterranean",
"Taramosalata": "https://source.unsplash.com/640x420/?taramosalata,fish,greek",
"Tiropita": "https://source.unsplash.com/640x420/?tiropita,cheese,greek",
"Koulouri": "https://source.unsplash.com/640x420/?koulouri,sesame,greek",
"Bougatsa": "https://source.unsplash.com/640x420/?bouga,cream,greek",
"Karydopita": "https://source.unsplash.com/640x420/?karydopita,walnuts,greek",
"Moustokouloura": "https://source.unsplash.com/640x420/?moustokouloura,grapes,greek",
"Diples": "https://source.unsplash.com/640x420/?diples,honey,greek",
"Pasteli": "https://source.unsplash.com/640x420/?pasteli,sesame,greek",
"Halvas": "https://source.unsplash.com/640x420/?halvas,semolina,greek",
"Briam": "https://source.unsplash.com/640x420/?briam,vegetables,greek",
"Lahanodolmades": "https://source.unsplash.com/640x420/?lahanodolmades,cabbage,greek",
"Kouneli Stifado": "https://source.unsplash.com/640x420/?kouneli,rabbit,greek",
"Arni Stifado": "https://source.unsplash.com/640x420/?arni,lamb,greek",
"Moshari Stifado": "https://source.unsplash.com/640x420/?moshari,beef,greek",
"Kokkinisto": "https://source.unsplash.com/640x420/?kokkinisto,beef,greek",
"Stifado": "https://source.unsplash.com/640x420/?stifado,beef,greek",
"Youvetsi": "https://source.unsplash.com/640x420/?youvetsi,lamb,greek",
"Kalamaki": "https://source.unsplash.com/640x420/?kalamaki,skewers,greek",
"Kotopoulo Souvlaki": "https://source.unsplash.com/640x420/?kotopoulo,chicken,greek",
"Paidakia": "https://source.unsplash.com/640x420/?paidakia,lamb,greek",
"Brizoles": "https://source.unsplash.com/640x420/?brizoles,pork,greek",
"Kontosouvli": "https://source.unsplash.com/640x420/?kontosouvli,pork,greek",
"Exohiko": "https://source.unsplash.com/640x420/?exohiko,lamb,greek",
"Soutzoukakia": "https://source.unsplash.com/640x420/?soutzoukakia,meatballs,greek",
"Keftedakia": "https://source.unsplash.com/640x420/?keftedakia,meatballs,greek",
"Giouvetsi": "https://source.unsplash.com/640x420/?giouvetsi,beef,greek",
"Papoutsakia": "https://source.unsplash.com/640x420/?papoutsakia,eggplant,greek",
"Imam Baildi": "https://source.unsplash.com/640x420/?imambaildi,eggplant,greek",
"Bamies Kokkinistes": "https://source.unsplash.com/640x420/?bamieskokkinistes,okra,greek",
"Kreatopita": "https://source.unsplash.com/640x420/?kreatopita,meat,greek",
"Kolokithopita": "https://source.unsplash.com/640x420/?kolokithopita,zucchini,greek",
"Marathopita": "https://source.unsplash.com/640x420/?marathopita,fennel,greek",
"Prasopita": "https://source.unsplash.com/640x420/?prasopita,leeks,greek",
"Tyropita": "https://source.unsplash.com/640x420/?tyropita,cheese,greek",
"Pantremeni": "https://source.unsplash.com/640x420/?pantremeni,salad,greek",
"Maroulosalata": "https://source.unsplash.com/640x420/?maroulosalata,lettuce,greek",
"Kolokythosalata": "https://source.unsplash.com/640x420/?kolokythosalata,zucchini,greek",
"Patatosalata": "https://source.unsplash.com/640x420/?patatosalata,potatoes,greek",
"Skordalia": "https://source.unsplash.com/640x420/?skordalia,garlic,greek",
"Melitzanosalata": "https://source.unsplash.com/640x420/?melitzanosalata,eggplant,greek",
"Fava": "https://source.unsplash.com/640x420/?fava,yellow,split,peas,greek",
"Revithia": "https://source.unsplash.com/640x420/?revithia,chickpeas,greek",
"Fasolia": "https://source.unsplash.com/640x420/?fasolia,beans,greek",
"Anginares": "https://source.unsplash.com/640x420/?anginares,artichokes,greek",
"Horta": "https://source.unsplash.com/640x420/?horta,greens,greek",
"Vrasto": "https://source.unsplash.com/640x420/?vrasto,boiled,greek",
"Bakaliaro": "https://source.unsplash.com/640x420/?bakaliaro,cod,greek",
"Gavros": "https://source.unsplash.com/640x420/?gavros,anchovies,greek",
"Sardelles": "https://source.unsplash.com/640x420/?sardelles,sardines,greek",
"Kalamarakia": "https://source.unsplash.com/640x420/?kalamarakia,squid,greek",
"Octapodi": "https://source.unsplash.com/640x420/?octapodi,octopus,greek",
"Barbunia": "https://source.unsplash.com/640x420/?barbunia,mussels,greek",
"Mydia": "https://source.unsplash.com/640x420/?mydia,clams,greek",
"Astakos": "https://source.unsplash.com/640x420/?astakos,lobster,greek",
"Kavouros": "https://source.unsplash.com/640x420/?kavouros,crab,greek",
"Garides": "https://source.unsplash.com/640x420/?garides,shrimp,greek",
"Psari": "https://source.unsplash.com/640x420/?psari,fish,greek",
"Sinarisma": "https://source.unsplash.com/640x420/?sinarisma,baked,greek",
"Plaki": "https://source.unsplash.com/640x420/?plaki,baked,greek",
"Stifado": "https://source.unsplash.com/640x420/?stifado,stewed,greek",
"Kokkinisto": "https://source.unsplash.com/640x420/?kokkinisto,red,sauce,greek",
"Yiahni": "https://source.unsplash.com/640x420/?yiahni,stewed,greek",
"Fourneto": "https://source.unsplash.com/640x420/?fourneto,oven,greek",
"Katsiki": "https://source.unsplash.com/640x420/?katsiki,goat,greek",
"Moschari": "https://source.unsplash.com/640x420/?moschari,beef,greek",
"Htapodi": "https://source.unsplash.com/640x420/?htapodi,octopus,greek",
"Kalamaras": "https://source.unsplash.com/640x420/?kalamaras,squid,greek",
"Psaro": "https://source.unsplash.com/640x420/?psaro,fish,greek",
"Mydopoda": "https://source.unsplash.com/640x420/?mydopoda,shellfish,greek",
"Oktapodi": "https://source.unsplash.com/640x420/?oktapodi,octopus,greek",
"Smyrna": "https://source.unsplash.com/640x420/?smyrna,spiced,greek",
"Vasilopita": "https://source.unsplash.com/640x420/?vasilopita,cake,greek",
"Tsoureki": "https://source.unsplash.com/640x420/?tsoureki,bread,greek",
"Lagana": "https://source.unsplash.com/640x420/?lagana,flatbread,greek",
"Foties": "https://source.unsplash.com/640x420/?foties,flatbread,greek",
"Koulouria": "https://source.unsplash.com/640x420/?koulouria,biscuits,greek",
"Ekmek": "https://source.unsplash.com/640x420/?ekmek,custard,greek",
};